# Generated by Django 4.2.20 on 2025-04-18 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoupload',
            old_name='uploaded_at',
            new_name='upload_time',
        ),
        migrations.RemoveField(
            model_name='videoupload',
            name='classification_result',
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
