# Generated by Django 4.2.20 on 2025-04-18 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_content_diagnosis_diagnosis_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolechangehistory',
            old_name='changed_at',
            new_name='change_date',
        ),
        migrations.RemoveField(
            model_name='rolechangehistory',
            name='changed_by',
        ),
        migrations.AddField(
            model_name='rolechangehistory',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin_role_changes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rolechangehistory',
            name='new_role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rolechangehistory',
            name='old_role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rolechangehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_changes', to=settings.AUTH_USER_MODEL),
        ),
    ]
